"""
Django settings for InfoRetrSys project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from mongoengine import connect
from mongoengine import *
import time
from django.utils import timezone
# 加载词典
import jieba.posseg
jieba.load_userdict("userdict.txt")

# 加载同义词词典
samewords_go = open('./samewords.txt', "r", encoding='utf-8-sig')
samewords = {}
basedata = {}
for line in samewords_go:
    seperate_word = line.strip().split()
    basedata[seperate_word[0]] = seperate_word
    num = len(seperate_word)
    samewords[seperate_word[0]] = seperate_word[0]
    for i in range(1, num):
        samewords[seperate_word[i]] = seperate_word[0]

# 加载停用词词典
stopwords_go = open('./stopwords.txt', 'r', encoding='utf-8-sig').readlines()
stopwords = [line.strip() for line in stopwords_go]

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i7y^8()2cejaf^etbuo(6=q$^9dk97&9i3ui-*$96kh-6i&mg*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'adminworkstation.apps.AdminworkstationConfig',
    'userworkstation.apps.UserworkstationConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'InfoRetrSys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InfoRetrSys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
connect('mydb', host='127.0.0.1', port=27017)
# DBNAME = 'mydb’
# SESSION_ENGINE = 'mongoengine.django.sessions'
### 数据库做以下配置 ###
DATABASES = {
    'default': {
        'ENGINE':'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    }
}

AUTH_USER_MODE= 'mongo_auth.MongoUser'
SESSION_COOKIE_AGE = 300
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# DATABASES = {
#     'default': {
        # 'ENGINE': 'django.db.backends.mysql',
        # 'NAME': 'mydb',
        # 'USER': 'root',
        # 'PASSWORD': 'mysqlpassword',
        # 'HOST': '',
        # 'PORT': '',
        # 'TEST': {
        #     'NAME': 'auto_tests',
        #     'CHARSET': 'utf8',
        # }
#    }
# }
LOG_PATH = os.path.join(BASE_DIR, 'LOG')


LOGGING = {
    'version': 1,  # 指明dictConnfig的版本，目前就只有一个版本
    'disable_existing_loggers': False,  # False表示是否禁用所有的已经存在的日志配置
    'formatters': {
        'default': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'},
        'simple': {
            # 'format': '[%(asctime)s] [%(levelname)s] %(message)s'},
            'format': '<%(asctime)s> | <%(levelname)s> | %(message)s'},

          },

    # handlers：用来定义具体处理日志的方式，可以定义多种，"default"就是默认方式，"console"就是打印到控制台方式。file是写入到文件的方式，注意使用的class不同
    'handlers': {  # 处理器，在这里定义了两个处理器

        'console': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            #'filename': '%s/log_%s.txt' % (LOG_PATH, datetime.datetime.now().strftime('%Y-%m-%d-%H-%M')),
            #'filename': os.path.join(LOG_PATH, 'log_{}.txt'.format(time.strftime('%Y-%m-%d-%H-%M'))),
            'filename': '%s/alllog' % (LOG_PATH),
            'when': 'midnight',
            'interval': 1,
            #'maxBytes': 5 * 1024 * 1024,
            'formatter': 'simple'  # 制定输出的格式，注意 在上面的formatters配置里面选择一个，否则会报错
        },

        'err': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            #'maxBytes': 100,
            # 'stream': 'ext://sys.stdout',   # 文件重定向的配置，将打印到控制台的信息都重定向出去 python manage.py runserver >> /home/aea/log/test.log
            #'filename': '%s/err_%s.txt' % (LOG_PATH, datetime.datetime.now().strftime('%Y-%m-%d-%H-%M')),
            'filename': '%s/errorlog' % (LOG_PATH),
            'when': 'midnight',
            'interval': 1,
            'formatter': 'simple'  # 制定输出的格式，注意 在上面的formatters配置里面选择一个，否则会报错
        },

        'custom': {
            'level': 'DEBUG',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            # 'filename': '%s/log_%s.txt' % (LOG_PATH, datetime.datetime.now().strftime('%Y-%m-%d-%H-%M')),
            # 'filename': os.path.join(LOG_PATH, 'log_{}.txt'.format(time.strftime('%Y-%m-%d-%H-%M'))),
            'filename': '%s/collectlog' % (LOG_PATH),
            'when': 'midnight',
            'interval': 1,
            # 'maxBytes': 5 * 1024 * 1024,
            'formatter': 'simple'  # 制定输出的格式，注意 在上面的formatters配置里面选择一个，否则会报错
        },

    },
    #
    'loggers': {

        # 用户输入的日志
        'cons': {
            'handlers': ['console'],
            'level': 'INFO'
        },

        'custom':{
            'handlers': ['custom'],
            'level': 'INFO'
        },

        # 出现的报错信息
        'err': {
            'handlers': ['err'],
            'level': 'INFO'
        }

    },

}



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

# add by wangshibin 20190720
LANGUAGE_CODE = 'zh-hans'
# add by wangshibin 20190720
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/InfoRetrSys/static'
]
